spring:
  profiles: default
eureka:
  client:
    ShouldFetchRegistry: false
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
server:
  port: 8082
