spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  
  tracing:
    exporter:
      zipkin:
        endpoint: http://tracing-server:9411/api/v2/spans
server:
  port: 8082
eureka:
  client:
    serviceUrl: http://discovery-server:8761/eureka/ #STEELTOE
    #serviceUrl:
    #  defaultZone: http://discovery-server:8761/eureka/ #SPRING